CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT UNIQUE NOT NULL,
    first_name TEXT NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS teams (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TEAM_NAME TEXT NOT NULL,
    TEAM_LOCATION TEXT NOT NULL,
    NUMBER_OF_TEAM_MEMBERS INTEGER NOT NULL,
    EMAIL_ADDRESS TEXT NOT NULL UNIQUE, 
    PHONE_NUMBER INTEGER NOT NULL
);


