CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT UNIQUE NOT NULL,
    first_name TEXT NOT NULL,
    password TEXT NOT NULL
    role TEXT 

);

ALTER TABLE users ADD COLUMN is_admin INTEGER DEFAULT 0;


CREATE TABLE IF NOT EXISTS teams (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,     
    TEAM_NAME TEXT NOT NULL,                   
    TEAM_LOCATION TEXT NOT NULL,                
    NUMBER_OF_TEAM_MEMBERS INTEGER NOT NULL CHECK (NUMBER_OF_TEAM_MEMBERS > 0),  
    EMAIL_ADDRESS TEXT NOT NULL UNIQUE,         
    PHONE_NUMBER TEXT NOT NULL           
);

-- CREATE TABLE IF NOT EXISTS contacts (
--     ID INTEGER PRIMARY KEY AUTOINCREMENT,
--     NAME TEXT NOT NULL,
--     EMAIL_ADDRESS TEXT NOT NULL UNIQUE,
--     PHONE_NUMBER TEXT NOT NULL UNIQUE,
--     TEAM_ID INTEGER NOT NULL,
--     FOREIGN KEY (TEAM_ID) REFERENCES teams(ID) ON DELETE CASCADE
-- );

DROP TABLE IF EXISTS contacts;


CREATE TABLE contacts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    employee_name TEXT,
    email_address TEXT,
    phone_number TEXT,
    team_id INTEGER,
    FOREIGN KEY (team_id) REFERENCES teams(id)
);
